"""
Django settings for vanguard_labs project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from decouple import config  # pip install python-decouple

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# -------------------------------------------------------------------
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-ae1z@lqj)m39j-wqf+b^oc)psf&+k#g)#ku#asjlq5t=%*9&2o')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')

# -------------------------------------------------------------------
# Application definition

INSTALLED_APPS = [
    # Django built‑ins
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',          # for sitemap.xml

    # Third‑party (for production static serving)
    'whitenoise.runserver_nostatic',    # replaces default static handler

    # Custom apps (all 20 apps from the project)
    'accounts',
    'analytics',
    'blog',
    'careers',
    'clients',
    'cms',
    'contact',
    'core',
    'crm',
    'events',
    'knowledgebase',
    'messaging',
    'notifications',
    'portfolio',
    'projects_management',
    'proposals',
    'services',
    'team',
    'testimonials',
]

MIDDLEWARE = [
    # Security & performance
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',   # static file serving (must be after SecurityMiddleware)

    # Django core
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'vanguard_labs.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],          # project‑level templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',   # required for admin & sitemaps
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Custom context processors
                'core.context_processors.site_settings',
                'core.context_processors.maintenance_mode',   # if defined
                'cms.context_processors.site_config',         # if using CMS site config
                'notifications.context_processors.unread_notifications_count',
                'testimonials.context_processors.featured_testimonials',  # optional
            ],
        },
    },
]

WSGI_APPLICATION = 'vanguard_labs.wsgi.application'

# -------------------------------------------------------------------
# Database – SQLite only
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# -------------------------------------------------------------------
# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

# -------------------------------------------------------------------
# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# -------------------------------------------------------------------
# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# -------------------------------------------------------------------
# Static & Media files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']          # additional static directories
STATIC_ROOT = BASE_DIR / 'staticfiles'            # where collectstatic puts files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# -------------------------------------------------------------------
# Login / Authentication redirects
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'core:home'      # or 'accounts:profile'
LOGOUT_REDIRECT_URL = 'core:home'

# -------------------------------------------------------------------
# Email configuration (modular – can be replaced with SMTP later)
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@vanguardlabs.com')
CONTACT_ADMIN_EMAIL = config('CONTACT_ADMIN_EMAIL', default='admin@vanguardlabs.com')
CONTACT_SEND_EMAIL = config('CONTACT_SEND_EMAIL', default=False, cast=bool)

# -------------------------------------------------------------------
# Site name (used in templates / context processors)
SITE_NAME = 'Vanguard Labs'
SITE_DOMAIN = config('SITE_DOMAIN', default='localhost:8000')

# -------------------------------------------------------------------
# Security settings for production
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000          # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # Ensure all hosts are allowed in production
    ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='').split(',')

# -------------------------------------------------------------------
# Maintenance mode flag (used by core context processor)
ENABLE_MAINTENANCE_MODE = config('ENABLE_MAINTENANCE_MODE', default=False, cast=bool)

# -------------------------------------------------------------------
# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# -------------------------------------------------------------------
# Optional: Caching (for rate‑limiting and search)
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
#         'LOCATION': 'unique-snowflake',
#     }
# }
